[project]
name = "text-2-shorts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "boto3==1.43.37",
    "fastapi==0.138.2",
    "requests>=2.32",
    "streamlit>=1.31",
    "langchain-aws>=1.6.0",
    "langgraph==1.2.7",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.0",
    "pyrefly>=0.60.0",
    "python-dotenv>=1.0",
    "typing-extensions>=4.15.0",
    "uvicorn>=0.30",
    "contextvars>=2.4",
    "boto3-stubs==1.43.37",
    "google-genai>=2.10.0",
    "tenacity>=9.0",
    "protobuf==7.35.1",
    "langgraph-checkpoint-sqlite>=3.1.0",
    "av==17.1.0",
    "beautifulsoup4==4.15.0",
    "cloup==3.1.0",
    "decorator==5.3.1",
    "glcontext==3.0.0",
    "isosurfaces==0.1.2",
    "manim==0.19.2",
    "manimpango==0.6.1",
    "mapbox-earcut==2.0.0",
    "markdown-it-py==4.2.0",
    "mdurl==0.1.2",
    "moderngl==5.12.0",
    "moderngl-window==3.1.1",
    "networkx==3.6.1",
    "pycairo==1.29.0",
    "pydub==0.25.1",
    "pyglet==2.1.15",
    "pyglm==2.8.3",
    "pygments==2.20.0",
    "rich==15.0.0",
    "scipy==1.16.2",
    "screeninfo==0.8.1",
    "soupsieve==2.8.4",
    "srt==3.5.3",
    "svgelements==1.9.6",
    "tqdm==4.68.3",
    "poolgate",
]

[tool.uv.sources]
poolgate = { git = "ssh://git@github.com/GARV-PATEL-11/PoolGate.git" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
